---
title: "Introduction to Statistics using R and RStudio"
author: "Mark Andrews"
location: Online
subtitle: '3-4 April, 2024'
date: '3 April, 2024'
description: "This two-day course provides a comprehensive introduction to R
and RStudio for data science and statistics in academic or professional
settings. It covers the fundamentals of R and the R environment, data
wrangling, data visualization, RMarkdown, and an introduction to statistics
using R."
categories: ["R", "RStudio", "Data Visualization"]
---

In this two day course, you will obtain a comprehensive introduction to R and RStudio and how it can be used for data science and statistics in an academic or professional setting.

This course is aimed at anyone who is interested in using R for data science or statistics. R is widely used in all areas of academic scientific research, and also widely throughout the public, and private sector.

The course will cover these key topics:

* The ‘what and why of R’; what is used for, and how it works.
* RStudio – a tour of the most widely used interface to R and how to use it effectively
* Fundamentals of R and the R environment, including variables and assignment, data structures (such as vectors and data frames), operations on data structures, functions, scripts, installing and loading packages, using RStudio projects and reading in data
* Data wrangling; the art of cleaning and restructuring data (focusing on filtering, slicing, selecting, renaming, and mutating data frames)
* Data visualization with an introduction to ggplot, scatterplots, boxplots and histograms
* RMarkdown, a powerful tool for creating reproducible research reports, as well as slides, scientific website and posters
* An introduction to statistics using R (linear regression, anova, and some other simple tests).

The course will take 6 contact hours per day plus two 2-hour breaks. The sessions will be as follows:

* Session 1: 9:30am-11:30am;
* Session 2: 12:30am-2:30pm;
* Session 3: 3:30pm-17:30pm

## Tutor Profile

Mark Andrews is an Associate Professor at Nottingham Trent University whose research and teaching is focused on statistical methodology in research in the social and biological sciences. He is the author of 2021 textbook on data science using R that is aimed at scientific researchers, and has a forthcoming new textbook on statistics and data science that is aimed at undergraduates in science courses. His background is in computational cognitive science and mathematical psychology.

